
services:
  vllm-rocm-amelia:
    image: vllm-rocm-amelia
    working_dir: /workspace/amelia-benchmark
    container_name: ${CONTAINER_NAME}
    network_mode: host
    group_add:
      - video
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/kfd
      - /dev/dri
    volumes:
      - ${CACHE_DIR}:/root/.cache
      - ./:/workspace/amelia-benchmark
    ports:
      - "8000:8000"
    environment:
      - MODEL=${MODEL}
      - API_KEY=${API_KEY}
    command: bash
    stdin_open: true
    tty: true
    
